# Generated by Django 4.2.29 on 2026-04-03 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_chronic_conditions_patient_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0003_visit_assigned_clinician_and_room'),
        ('branches', '0003_branch_shift_variance_threshold'),
        ('admission', '0005_alter_admission_bed_alter_admission_ward_ward_bed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted to Labour Ward'), ('in_labour', 'In Labour'), ('delivered', 'Delivered'), ('post_delivery', 'Post-Delivery Observation'), ('discharged', 'Discharged')], default='admitted', max_length=20)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('labour_started_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('delivery_type', models.CharField(blank=True, choices=[('normal', 'Normal Vaginal Delivery'), ('caesarean', 'Caesarean Section'), ('assisted', 'Assisted Delivery (Vacuum/Forceps)'), ('breech', 'Breech Delivery')], max_length=20)),
                ('baby_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('ambiguous', 'Ambiguous')], max_length=10)),
                ('baby_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Baby weight in kilograms', max_digits=4, null=True)),
                ('apgar_score_1min', models.PositiveSmallIntegerField(blank=True, help_text='APGAR at 1 min (0-10)', null=True)),
                ('apgar_score_5min', models.PositiveSmallIntegerField(blank=True, help_text='APGAR at 5 min (0-10)', null=True)),
                ('outcome', models.CharField(blank=True, choices=[('live_birth', 'Live Birth'), ('still_birth', 'Still Birth'), ('neonatal_death', 'Neonatal Death')], max_length=20)),
                ('gravida', models.PositiveSmallIntegerField(blank=True, help_text='Number of pregnancies', null=True)),
                ('parity', models.PositiveSmallIntegerField(blank=True, help_text='Number of previous deliveries', null=True)),
                ('gestational_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('complications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('discharge_datetime', models.DateTimeField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='admission.admission')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries_performed', to=settings.AUTH_USER_MODEL)),
                ('midwife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_assisted', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='visits.visit')),
            ],
            options={
                'ordering': ['-admitted_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('labour_progress', 'Labour Progress'), ('vitals', 'Vitals'), ('medication', 'Medication'), ('observation', 'Observation'), ('handover', 'Shift Handover')], default='observation', max_length=20)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_delivery_notes', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='delivery.deliveryrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['branch', 'status'], name='delivery_de_branch__7552f0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['branch', 'admitted_at'], name='delivery_de_branch__781fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrecord',
            index=models.Index(fields=['patient', '-admitted_at'], name='delivery_de_patient_566c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['delivery', '-created_at'], name='delivery_de_deliver_d806a8_idx'),
        ),
    ]
