# Generated by Django 4.2.8 on 2026-04-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_shift_variance_threshold'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_order', models.PositiveSmallIntegerField(default=1, help_text='1 for single/first twin, 2 for second twin, etc.')),
                ('baby_name', models.CharField(blank=True, help_text='Optional baby name', max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('ambiguous', 'Ambiguous')], max_length=10)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Baby weight in kilograms', max_digits=4, null=True)),
                ('apgar_score_1min', models.PositiveSmallIntegerField(blank=True, help_text='APGAR at 1 min (0-10)', null=True)),
                ('apgar_score_5min', models.PositiveSmallIntegerField(blank=True, help_text='APGAR at 5 min (0-10)', null=True)),
                ('outcome', models.CharField(blank=True, choices=[('live_birth', 'Live Birth'), ('still_birth', 'Still Birth'), ('neonatal_death', 'Neonatal Death')], max_length=20)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Head circumference in cm', max_digits=4, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Baby length in cm', max_digits=4, null=True)),
                ('resuscitation_needed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='delivery.deliveryrecord')),
            ],
            options={
                'ordering': ['birth_order'],
                'abstract': False,
                'indexes': [models.Index(fields=['delivery', 'birth_order'], name='delivery_ba_deliver_e9c844_idx')],
            },
        ),
    ]
