# Generated by Django 4.2.29 on 2026-03-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_dispenserecord_visit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispenserecord',
            new_name='pharmacy_di_branch__d39000_idx',
            old_name='pharmacy_di_branch__89dd31_idx',
        ),
        migrations.RenameIndex(
            model_name='dispenserecord',
            new_name='pharmacy_di_branch__c17413_idx',
            old_name='pharmacy_di_branch__e4f7dc_idx',
        ),
    ]
