# Generated by Django 4.2.29 on 2026-03-17 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockissue_stockitem_charge_rate_stockitem_is_active_and_more'),
        ('pharmacy', '0005_medicalstorerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstorerequest',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_requests', to='inventory.stockitem'),
        ),
    ]
