# Generated by Django 4.2.29 on 2026-03-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_pharmacyrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pharmacyrequest',
            new_name='pharmacy_ph_branch__4ed316_idx',
            old_name='pharmacy_ph_branch__ba1297_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyrequest',
            new_name='pharmacy_ph_branch__26eb60_idx',
            old_name='pharmacy_ph_branch__a018f6_idx',
        ),
    ]
