# Generated by Django 4.2.29 on 2026-04-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_invoice_walk_in_customer_name_and_more'),
        ('pharmacy', '0017_walkinsale_walkinsaleline_pharmacyshift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinsale',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walkin_sales', to='billing.invoice'),
        ),
    ]
