# Generated by Django 4.2.29 on 2026-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_walkinsale_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='e.g. Tablet, Syrup, Injection', max_length=30),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. 500mg, 250mg/5ml', max_length=120),
        ),
    ]
