# Generated by Django 4.2.29 on 2026-03-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(max_length=24, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('next_of_kin', models.CharField(max_length=120)),
                ('next_of_kin_phone', models.CharField(max_length=30)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('allergies', models.TextField(blank=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'last_name', 'first_name'], name='patients_pa_branch__d88b06_idx')],
            },
        ),
    ]
