# Generated by Django 4.2.29 on 2026-04-04 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0003_visit_assigned_clinician_and_room'),
        ('branches', '0003_branch_shift_variance_threshold'),
        ('patients', '0002_patient_chronic_conditions_patient_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('triage', 'Triage'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('admission', 'Admission'), ('pharmacy', 'Pharmacy'), ('referral', 'Referral'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['branch', 'patient', '-created_at'], name='patients_pa_branch__856f4f_idx')],
            },
        ),
    ]
