# Generated by Django 4.2.8 on 2026-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('system_admin', 'System Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('triage_officer', 'Triage Officer'), ('lab_technician', 'Laboratory Technician'), ('radiology_technician', 'Radiology Technician'), ('radiologist', 'Radiologist'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('receptionist', 'Receptionist')], default='receptionist', max_length=40),
        ),
    ]
