# Generated by Django 4.2.29 on 2026-03-14 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.CharField(max_length=100)),
                ('bed', models.CharField(max_length=40)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField()),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'admission_date'], name='admission_a_branch__4eef8c_idx')],
            },
        ),
    ]
