# Generated by Django 4.2.29 on 2026-03-27 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_shift_variance_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0003_admission_nurse_alter_admission_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Observation'), ('vitals', 'Vitals Update'), ('medication', 'Medication Administration'), ('wound_care', 'Wound Care'), ('intake_output', 'Intake / Output'), ('handover', 'Shift Handover')], default='general', max_length=20)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='admission.admission')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['admission', '-created_at'], name='admission_n_admissi_b221f8_idx')],
            },
        ),
    ]
