# Generated by Django 4.2.29 on 2026-04-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_triagerecord_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerecord',
            name='auto_notes',
            field=models.TextField(blank=True, verbose_name='Clinical Auto-Notes'),
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='priority_score',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Low concern'), (3, 'Moderate'), (4, 'High'), (5, 'Critical')], default=1),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='blood_pressure',
            field=models.CharField(help_text='mmHg (e.g. 120/80)', max_length=20),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='cm', max_digits=6),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='oxygen_level',
            field=models.PositiveIntegerField(help_text='SpO₂ %'),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='pulse_rate',
            field=models.PositiveIntegerField(help_text='bpm'),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='respiratory_rate',
            field=models.PositiveIntegerField(help_text='breaths/min'),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='temperature',
            field=models.DecimalField(decimal_places=2, help_text='°C', max_digits=5),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='kg', max_digits=6),
        ),
    ]
