# Generated by Django 4.2.29 on 2026-04-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_triagerecord_auto_notes_triagerecord_priority_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerecord',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('A+', 'A+'), ('A-', 'A−'), ('B+', 'B+'), ('B-', 'B−'), ('AB+', 'AB+'), ('AB-', 'AB−'), ('O+', 'O+'), ('O-', 'O−')], default='', max_length=5),
        ),
    ]
