# Generated by Django 4.2.29 on 2026-03-17 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0002_remove_branch_date_created'),
        ('pharmacy', '0004_rename_pharmacy_di_branch__89dd31_idx_pharmacy_di_branch__d39000_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStoreRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_store_requests_handled', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_store_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['branch', 'status', 'created_at'], name='pharmacy_me_branch__ee671a_idx'), models.Index(fields=['branch', 'medicine_name'], name='pharmacy_me_branch__c4a44f_idx')],
            },
        ),
    ]
