# Generated by Django 4.2.29 on 2026-03-17 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('pharmacy', '0006_medicalstorerequest_stock_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenserecord',
            name='sale_type',
            field=models.CharField(choices=[('prescription', 'Doctor Prescription'), ('walk_in', 'Walk-In Sale')], default='prescription', max_length=20),
        ),
        migrations.AddField(
            model_name='dispenserecord',
            name='walk_in_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dispenserecord',
            name='walk_in_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dispenserecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
    ]
