# Generated by Django 4.2.29 on 2026-03-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_shift_variance_threshold'),
        ('pharmacy', '0015_medicalstorerequest_decision_remarks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispensebatchallocation',
            new_name='pharmacy_di_branch__7a3426_idx',
            old_name='pharmacy_di_branch__a39ce6_idx',
        ),
        migrations.RenameIndex(
            model_name='dispensebatchallocation',
            new_name='pharmacy_di_branch__910180_idx',
            old_name='pharmacy_di_branch__ecbc20_idx',
        ),
        migrations.RenameIndex(
            model_name='dispensebatchallocation',
            new_name='pharmacy_di_branch__b067b1_idx',
            old_name='pharmacy_di_branch__0b55d8_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalstorerequest',
            new_name='pharmacy_me_branch__5c7e1b_idx',
            old_name='pharmacy_me_branch__781f16_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalstorerequest',
            new_name='pharmacy_me_branch__236c17_idx',
            old_name='pharmacy_me_branch__a7b7f8_idx',
        ),
        migrations.RenameIndex(
            model_name='medicine',
            new_name='pharmacy_me_branch__907eb4_idx',
            old_name='pharmacy_me_branch__11f183_idx',
        ),
        migrations.AlterField(
            model_name='dispensebatchallocation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch'),
        ),
    ]
