# Generated by Django 4.2.8 on 2026-03-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        choices=[
                            ("patients", "Patients"),
                            ("triage", "Triage"),
                            ("consultation", "Consultation"),
                            ("laboratory", "Laboratory"),
                            ("radiology", "Radiology"),
                            ("pharmacy", "Pharmacy"),
                            ("billing", "Billing"),
                            ("admission", "Admission"),
                            ("emergency", "Emergency"),
                            ("referrals", "Referrals"),
                            ("inventory", "Inventory"),
                            ("visits", "Visits"),
                            ("reports", "Reports"),
                        ],
                        max_length=40,
                    ),
                ),
                ("can_soft_delete", models.BooleanField(default=False)),
                ("can_hard_delete", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="module_permission_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["module_name"], name="permission_m_module__77f822_idx"
                    ),
                    models.Index(
                        fields=["user", "module_name"],
                        name="permission_m_user_id_60018d_idx",
                    ),
                ],
                "unique_together": {("user", "module_name")},
            },
        ),
    ]
