# Generated by Django 4.2.29 on 2026-03-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_expand_module_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usermodulepermission',
            new_name='permissions_module__77f034_idx',
            old_name='permission_m_module__77f822_idx',
        ),
        migrations.RenameIndex(
            model_name='usermodulepermission',
            new_name='permissions_user_id_675425_idx',
            old_name='permission_m_user_id_60018d_idx',
        ),
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module_name',
            field=models.CharField(choices=[('patients', 'Patients'), ('triage', 'Triage'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing'), ('admission', 'Admission'), ('emergency', 'Emergency'), ('referrals', 'Referrals'), ('inventory', 'Inventory'), ('visits', 'Visits'), ('reports', 'Reports'), ('accounts', 'Accounts'), ('permissions', 'Permissions'), ('branches', 'Branches'), ('settingsapp', 'System Settings'), ('core', 'Core Dashboards')], max_length=40),
        ),
    ]
