# Generated by Django 4.2.29 on 2026-04-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_permissionaccessrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='permissionaccessrequest',
            new_name='permissions_status_808649_idx',
            old_name='permissions_access_status_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionaccessrequest',
            new_name='permissions_user_id_74c24c_idx',
            old_name='permissions_access_user_mod_idx',
        ),
        migrations.AlterField(
            model_name='permissionaccessrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
