# Generated by Django 4.2.8 on 2026-04-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_rename_permissions_access_status_idx_permissions_status_808649_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionaccessrequest',
            name='module_name',
            field=models.CharField(choices=[('patients', 'Patients'), ('triage', 'Triage'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing'), ('admission', 'Admission'), ('delivery', 'Delivery Ward'), ('emergency', 'Emergency'), ('referrals', 'Referrals'), ('inventory', 'Inventory'), ('visits', 'Visits'), ('reports', 'Reports'), ('accounts', 'Accounts'), ('permissions', 'Permissions'), ('branches', 'Branches'), ('settingsapp', 'System Settings'), ('core', 'Core Dashboards')], max_length=40),
        ),
        migrations.AlterField(
            model_name='usermodulepermission',
            name='module_name',
            field=models.CharField(choices=[('patients', 'Patients'), ('triage', 'Triage'), ('consultation', 'Consultation'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('billing', 'Billing'), ('admission', 'Admission'), ('delivery', 'Delivery Ward'), ('emergency', 'Emergency'), ('referrals', 'Referrals'), ('inventory', 'Inventory'), ('visits', 'Visits'), ('reports', 'Reports'), ('accounts', 'Accounts'), ('permissions', 'Permissions'), ('branches', 'Branches'), ('settingsapp', 'System Settings'), ('core', 'Core Dashboards')], max_length=40),
        ),
    ]
