# Generated by Django 4.2.8 on 2026-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='export_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], default='csv', max_length=10),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['branch', 'report_type', 'generated_at'], name='reports_gen_branch__34172e_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['generated_by', 'generated_at'], name='reports_gen_generat_e399e1_idx'),
        ),
    ]
