# Generated by Django 4.2.29 on 2026-03-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_rename_visits_visi_branch__eb95ff_idx_visits_visi_branch__6ac241_idx_and_more'),
        ('billing', '0002_invoice_date_and_line_items'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoicelineitem',
            new_name='billing_inv_branch__2f943f_idx',
            old_name='billing_inv_branch__b166f8_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicelineitem',
            new_name='billing_inv_source__a3c113_idx',
            old_name='billing_inv_source__c4b6ad_idx',
        ),
        migrations.AddField(
            model_name='invoice',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='visits.visit'),
        ),
    ]
