# Generated by Django 4.2.29 on 2026-03-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_billing_inv_branch__b166f8_idx_billing_inv_branch__2f943f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab Test'), ('radiology', 'Radiology Scan'), ('pharmacy', 'Pharmacy Medicine'), ('referral', 'Referral')], max_length=20),
        ),
    ]
