# Generated by Django 4.2.29 on 2026-03-17 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_remove_branch_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_invoicelineitem_stock_deducted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDrawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab Test'), ('radiology', 'Radiology Scan'), ('pharmacy', 'Pharmacy Medicine'), ('referral', 'Referral')], max_length=20)),
                ('drawer_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cash_drawers', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceLinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance')], max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('drawer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.cashdrawer')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoicelineitem')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['branch', 'paid_at'], name='billing_inv_branch__47a690_idx'), models.Index(fields=['branch', 'drawer', 'paid_at'], name='billing_inv_branch__d63cba_idx'), models.Index(fields=['branch', 'received_by', 'paid_at'], name='billing_inv_branch__4f3068_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cashdrawer',
            index=models.Index(fields=['branch', 'service_type'], name='billing_cas_branch__647c69_idx'),
        ),
        migrations.AddIndex(
            model_name='cashdrawer',
            index=models.Index(fields=['branch', 'is_active'], name='billing_cas_branch__12fc70_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashdrawer',
            constraint=models.UniqueConstraint(fields=('branch', 'service_type'), name='billing_unique_branch_service_drawer'),
        ),
    ]
