# Generated by Django 4.2.29 on 2026-03-22 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_approvalrequest_financialsequenceanomaly'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='billing_app_branch__809baa_idx',
            old_name='billing_app_branch__9bde95_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='billing_app_approva_d69696_idx',
            old_name='billing_app_approva_2ec64e_idx',
        ),
        migrations.RenameIndex(
            model_name='financialsequenceanomaly',
            new_name='billing_fin_branch__53dc21_idx',
            old_name='billing_fin_branch__5328c7_idx',
        ),
        migrations.RenameIndex(
            model_name='financialsequenceanomaly',
            new_name='billing_fin_object__72248e_idx',
            old_name='billing_fin_object__4cd2fe_idx',
        ),
    ]
