# Generated by Django 4.2.29 on 2026-03-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0003_branch_shift_variance_threshold'),
        ('billing', '0012_rename_billing_cas_branch__7c32b0_idx_billing_cas_branch__df0d06_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='approval_type',
            field=models.CharField(choices=[('paid_rollback', 'Paid Status Rollback'), ('void_invoice', 'Void Invoice'), ('refund', 'Refund'), ('discount_override', 'Discount Override'), ('reopen_day', 'Reopen Day'), ('shift_variance', 'Shift Variance Approval'), ('partial_payment', 'Partial Payment Approval')], max_length=40),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=40, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('insurance', 'Insurance')], max_length=20)),
                ('receipt_type', models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment')], default='full', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['branch', 'created_at'], name='billing_rec_branch__97945f_idx'), models.Index(fields=['invoice'], name='billing_rec_invoice_1a519f_idx')],
            },
        ),
    ]
