# Generated by Django 4.2.29 on 2026-03-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoicelineitem_profit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='stock_deducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
