# Generated by ChatGPT on 2026-03-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_remove_branch_date_created"),
        ("billing", "0008_backfill_line_payment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("paid_rollback", "Paid Status Rollback"),
                            ("void_invoice", "Void Invoice"),
                            ("refund", "Refund"),
                            ("discount_override", "Discount Override"),
                            ("reopen_day", "Reopen Day"),
                        ],
                        max_length=40,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                (
                    "requested_payment_method",
                    models.CharField(blank=True, max_length=20),
                ),
                ("reason", models.TextField()),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="branches.branch",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="billing.invoice",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FinancialSequenceAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("anomaly_date", models.DateField()),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("duplicate_sequence", "Duplicate Sequence"),
                            ("missing_sequence", "Missing Sequence"),
                            ("invalid_format", "Invalid Format"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("invoice", "Invoice"), ("receipt", "Receipt")],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("reference_value", models.CharField(blank=True, max_length=120)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "detected_by",
                    models.CharField(default="sequence-check-command", max_length=80),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["branch", "status", "created_at"],
                name="billing_app_branch__9bde95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["approval_type", "status", "created_at"],
                name="billing_app_approva_2ec64e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialsequenceanomaly",
            index=models.Index(
                fields=["branch", "anomaly_date", "is_resolved"],
                name="billing_fin_branch__5328c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialsequenceanomaly",
            index=models.Index(
                fields=["object_type", "anomaly_type", "anomaly_date"],
                name="billing_fin_object__4cd2fe_idx",
            ),
        ),
    ]
