# Generated by Django 4.2.29 on 2026-03-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_cashiershiftsession_approvalrequest_cashier_shift'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashiershiftsession',
            new_name='billing_cas_branch__df0d06_idx',
            old_name='billing_cas_branch__7c32b0_idx',
        ),
        migrations.RenameIndex(
            model_name='cashiershiftsession',
            new_name='billing_cas_branch__f6f7d8_idx',
            old_name='billing_cas_branch__8cb955_idx',
        ),
    ]
