# Generated by Django 4.2.8 on 2026-03-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_backfill_invoice_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='service_description',
            field=models.CharField(blank=True, help_text='Human-readable description of services paid for', max_length=500),
        ),
        migrations.AddField(
            model_name='receipt',
            name='service_type',
            field=models.CharField(blank=True, help_text='Service category: consultation, lab, radiology, pharmacy, referral, or mixed', max_length=40),
        ),
    ]
