# Generated by Django 4.2.29 on 2026-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_receipt_service_description_receipt_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelinepayment',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=40),
        ),
        migrations.AddField(
            model_name='invoicelinepayment',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for bank transfers', max_length=100),
        ),
        migrations.AddField(
            model_name='invoicelinepayment',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4),
        ),
        migrations.AddField(
            model_name='invoicelinepayment',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoicelinepayment',
            name='network',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN'), ('airtel', 'Airtel'), ('other', 'Other')], help_text='Mobile money network', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicelinepayment',
            name='payer_phone',
            field=models.CharField(blank=True, help_text='Mobile money phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('insurance', 'Insurance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicelinepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('insurance', 'Insurance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('insurance', 'Insurance')], max_length=20),
        ),
    ]
