# Generated by Django 4.2.8 on 2026-04-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_invoicelinepayment_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrawer',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab Test'), ('radiology', 'Radiology Scan'), ('pharmacy', 'Pharmacy Medicine'), ('referral', 'Referral'), ('admission', 'Admission / Ward Charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab Test'), ('radiology', 'Radiology Scan'), ('pharmacy', 'Pharmacy Medicine'), ('referral', 'Referral'), ('admission', 'Admission / Ward Charge')], max_length=20),
        ),
    ]
