# Generated by Django 4.2.8 on 2026-04-03 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0020_alter_cashdrawer_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_line_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='cashier_authorized',
            field=models.BooleanField(default=True, help_text='Whether the cashier has authorized this charge. False = pending cashier approval before the service can be provided.'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['branch', 'cashier_authorized'], name='billing_inv_branch__b7b929_idx'),
        ),
    ]
