# Generated by Django 4.2.29 on 2026-04-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_chronic_conditions_patient_email_and_more'),
        ('billing', '0021_add_cashier_authorization_to_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='walk_in_customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='walk_in_customer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
    ]
