# Generated by Django 4.2.29 on 2026-04-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_invoice_walk_in_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_category',
            field=models.CharField(choices=[('opd', 'OPD'), ('inpatient', 'Inpatient')], default='opd', help_text='Separates OPD from inpatient billing.', max_length=10),
        ),
    ]
