# Generated by Django 4.2.29 on 2026-03-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0002_refactor_systemsettings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='primary_color',
            field=models.CharField(default='#125ea8', max_length=32),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='system_email',
            field=models.EmailField(max_length=254),
        ),
    ]
