# Generated by Django 4.2.29 on 2026-03-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0003_alter_systemsettings_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='dashboard_color',
            field=models.CharField(default='#f1f5f9', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='lab_service_rates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='radiology_service_rates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='text_color',
            field=models.CharField(default='#1e293b', max_length=32),
        ),
    ]
