# Generated by Django 4.2.29 on 2026-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsapp", "0006_systemsettings_sidebar_text_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="sidebar_active_color",
            field=models.CharField(default="#0d6efd", max_length=32),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="sidebar_heading_color",
            field=models.CharField(default="#cbd5e1", max_length=32),
        ),
    ]
