# Generated by Django 4.2.29 on 2026-03-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0007_systemsettings_sidebar_active_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='country',
            field=models.CharField(blank=True, default='Uganda', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
