# Generated by Django 4.2.8 on 2026-04-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0008_add_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ward_category_rates',
            field=models.JSONField(blank=True, default=dict, help_text='Daily rates per ward category, e.g. {"ordinary":"50000","vip":"150000","vvip":"300000"}'),
        ),
    ]
