# Generated by Django 4.2.29 on 2026-03-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_shift_variance_threshold'),
        ('inventory', '0010_inventorystoreprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorystoreprofile',
            new_name='inventory_i_branch__e1a46e_idx',
            old_name='inventory_i_branch__e56a4d_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='inventory_i_branch__663751_idx',
            old_name='inventory_i_branch__0ed3ec_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='inventory_i_branch__84cf77_idx',
            old_name='inventory_i_branch__6992af_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceconsumption',
            new_name='inventory_s_branch__affcd0_idx',
            old_name='inventory_s_branch__ef63a2_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceconsumption',
            new_name='inventory_s_branch__113a94_idx',
            old_name='inventory_s_branch__65751c_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceconsumption',
            new_name='inventory_s_branch__7fde5a_idx',
            old_name='inventory_s_branch__8310b9_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceconsumption',
            new_name='inventory_s_branch__cad4ec_idx',
            old_name='inventory_s_branch__3c08d0_idx',
        ),
        migrations.AlterField(
            model_name='serviceconsumption',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch'),
        ),
    ]
