# Generated by Django 4.2.29 on 2026-03-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_serviceconsumption_reversal_and_split_radiology_store'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serviceconsumption',
            new_name='inventory_s_branch__f123ee_idx',
            old_name='inventory_s_branch__d24f4f_idx',
        ),
    ]
