# Generated by Django 4.2.29 on 2026-03-27 18:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rename_inventory_s_branch__d24f4f_idx_inventory_s_branch__f123ee_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='target_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Target profit margin percentage used to auto-calculate selling price.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='batch',
            name='selling_price_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
