# Generated by Django 4.2.29 on 2026-04-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_stockmovement_movement_type_stocktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location/shelf within this store.', max_length=120),
        ),
        migrations.AddField(
            model_name='batch',
            name='selling_price_override',
            field=models.BooleanField(default=False, help_text='When True the selling price was manually set; margin auto-calc is disabled.'),
        ),
        migrations.AddField(
            model_name='item',
            name='batch_tracking',
            field=models.BooleanField(default=True, help_text='Track this item by batch/lot number.'),
        ),
        migrations.AddField(
            model_name='item',
            name='control_status',
            field=models.CharField(choices=[('none', 'Not Controlled'), ('prescription', 'Prescription Only'), ('controlled', 'Controlled Substance'), ('narcotic', 'Narcotic')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('supply', 'Healthcare Supply'), ('device', 'Medical Device')], default='medicine', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock-keeping unit code.', max_length=60),
        ),
        migrations.AddField(
            model_name='item',
            name='storage_class',
            field=models.CharField(choices=[('room_temp', 'Room Temperature'), ('cool', 'Cool (8-15°C)'), ('refrigerated', 'Refrigerated (2-8°C)'), ('frozen', 'Frozen (<-10°C)'), ('protected_light', 'Protected from Light')], default='room_temp', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='dosage_form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('capsule', 'Capsule'), ('drops', 'Drops'), ('ointment', 'Ointment'), ('solution', 'Solution'), ('suspension', 'Suspension'), ('powder', 'Powder'), ('gel', 'Gel'), ('suppository', 'Suppository'), ('inhaler', 'Inhaler'), ('patch', 'Patch'), ('device', 'Device'), ('reagent', 'Reagent'), ('consumable', 'Consumable'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['branch', 'sku'], name='inventory_i_branch__58deea_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['branch', 'item_type'], name='inventory_i_branch__2c8f49_idx'),
        ),
    ]
