# Generated by Django 4.2.29 on 2026-04-04 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0003_branch_shift_variance_threshold'),
        ('inventory', '0017_item_is_department_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='l1_name',
            field=models.CharField(blank=True, help_text="Level-1 packaging name, e.g. 'Strip' or 'Blister'.", max_length=60),
        ),
        migrations.AddField(
            model_name='item',
            name='l1_qty',
            field=models.PositiveIntegerField(default=0, help_text='How many base units make one L1 package.'),
        ),
        migrations.AddField(
            model_name='item',
            name='l2_name',
            field=models.CharField(blank=True, help_text="Level-2 packaging name, e.g. 'Box' or 'Inner carton'.", max_length=60),
        ),
        migrations.AddField(
            model_name='item',
            name='l2_qty',
            field=models.PositiveIntegerField(default=0, help_text='How many L1 packages make one L2 package.'),
        ),
        migrations.AddField(
            model_name='item',
            name='l3_name',
            field=models.CharField(blank=True, help_text="Level-3 packaging name, e.g. 'Carton' or 'Outer carton'.", max_length=60),
        ),
        migrations.AddField(
            model_name='item',
            name='l3_qty',
            field=models.PositiveIntegerField(default=0, help_text='How many L2 packages make one L3 package.'),
        ),
        migrations.AddField(
            model_name='item',
            name='min_sale_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity that can be sold/dispensed at once.'),
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent item for variant grouping (e.g. Panadol 500mg is a variant of Panadol).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('ADJUSTMENT', 'ADJUSTMENT'), ('EXPIRED', 'EXPIRED'), ('TRANSFER_OUT', 'TRANSFER_OUT'), ('TRANSFER_IN', 'TRANSFER_IN'), ('RETURN', 'RETURN')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('return_source', models.CharField(choices=[('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('ward', 'Ward / Admission')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_returns', to='inventory.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_returns', to='inventory.item')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_returns_initiated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_returns_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['branch', 'status', 'created_at'], name='inventory_s_branch__31b59c_idx'), models.Index(fields=['branch', 'item', 'created_at'], name='inventory_s_branch__3a127a_idx')],
            },
        ),
    ]
