# Generated by Django 4.2.29 on 2026-04-05 16:13

from decimal import Decimal
from django.db import migrations, models


def convert_percentage_to_factor(apps, schema_editor):
    """Convert existing target_margin values from percentage (e.g. 25.00)
    to multiplication factor (e.g. 1.25).  Only touch rows that look like
    the old percentage convention (value >= 2 implies it's still a %)."""
    Batch = apps.get_model("inventory", "Batch")
    for batch in Batch.objects.filter(target_margin__gte=Decimal("2.00")):
        batch.target_margin = Decimal("1.00") + batch.target_margin / Decimal("100")
        batch.save(update_fields=["target_margin"])


def convert_factor_to_percentage(apps, schema_editor):
    """Reverse: factor → percentage."""
    Batch = apps.get_model("inventory", "Batch")
    for batch in Batch.objects.all():
        if batch.target_margin >= Decimal("1.00"):
            batch.target_margin = (batch.target_margin - Decimal("1.00")) * Decimal(
                "100"
            )
            batch.save(update_fields=["target_margin"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0018_item_l1_name_item_l1_qty_item_l2_name_item_l2_qty_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="target_margin",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.25"),
                help_text="Multiplication factor applied to unit cost to get selling price (e.g. 1.25 = 25% markup).",
                max_digits=7,
            ),
        ),
        migrations.RunPython(
            convert_percentage_to_factor,
            reverse_code=convert_factor_to_percentage,
        ),
    ]
