# Generated by Django 4.2.29 on 2026-03-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockitem_department'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockitem',
            new_name='inventory_s_branch__a77392_idx',
            old_name='inventory_s_branch__f37fc3_idx',
        ),
    ]
