# Generated by Django 4.2.29 on 2026-03-17 21:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_remove_branch_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_rename_inventory_s_branch__f37fc3_idx_inventory_s_branch__a77392_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_to', models.CharField(choices=[('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('general', 'General')], max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='charge_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='service_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='service_type',
            field=models.CharField(blank=True, choices=[('', 'Not billable item'), ('lab', 'Laboratory Service'), ('radiology', 'Radiology Service'), ('consultation', 'Consultation')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='department',
            field=models.CharField(choices=[('medical_store', 'Medical Store'), ('laboratory', 'Laboratory Materials'), ('radiology', 'Radiology Materials'), ('pharmacy', 'Pharmacy'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['branch', 'service_type', 'service_code'], name='inventory_s_branch__322bc4_idx'),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.stockitem'),
        ),
        migrations.AddIndex(
            model_name='stockissue',
            index=models.Index(fields=['branch', 'issued_to', 'created_at'], name='inventory_s_branch__b91549_idx'),
        ),
        migrations.AddIndex(
            model_name='stockissue',
            index=models.Index(fields=['stock_item', 'created_at'], name='inventory_s_stock_i_a69526_idx'),
        ),
    ]
