from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_stockissue_stockitem_charge_rate_stockitem_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="branches.branch")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="branches.branch")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("contact", models.CharField(blank=True, max_length=120)),
                ("address", models.TextField(blank=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="branches.branch")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_name", models.CharField(max_length=255)),
                ("generic_name", models.CharField(blank=True, max_length=255)),
                ("dosage_form", models.CharField(choices=[("tablet", "Tablet"), ("syrup", "Syrup"), ("injection", "Injection"), ("cream", "Cream"), ("capsule", "Capsule"), ("drops", "Drops"), ("other", "Other")], max_length=30)),
                ("strength", models.CharField(blank=True, max_length=120)),
                ("unit_of_measure", models.CharField(max_length=60)),
                ("pack_size", models.CharField(blank=True, max_length=60)),
                ("barcode", models.CharField(blank=True, max_length=120)),
                ("reorder_level", models.PositiveIntegerField(default=10)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.brand")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="branches.branch")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.category")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Dispense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(blank=True, max_length=180)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="branches.branch")),
                ("dispensed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_dispenses", to=settings.AUTH_USER_MODEL)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="patients.patient")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_number", models.CharField(max_length=120)),
                ("mfg_date", models.DateField(blank=True, null=True)),
                ("exp_date", models.DateField()),
                ("quantity_received", models.PositiveIntegerField()),
                ("quantity_remaining", models.PositiveIntegerField(default=0)),
                ("purchase_price_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=14)),
                ("selling_price_per_unit", models.DecimalField(decimal_places=2, max_digits=14)),
                ("profit_margin", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=7)),
                ("barcode", models.CharField(blank=True, max_length=120)),
                ("weight", models.CharField(blank=True, max_length=60)),
                ("volume", models.CharField(blank=True, max_length=60)),
                ("date_received", models.DateField(default=django.utils.timezone.localdate)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="branches.branch")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_batches_created", to=settings.AUTH_USER_MODEL)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="batches", to="inventory.item")),
                ("supplier", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="batches", to="inventory.supplier")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("movement_type", models.CharField(choices=[("IN", "IN"), ("OUT", "OUT"), ("ADJUSTMENT", "ADJUSTMENT"), ("EXPIRED", "EXPIRED")], max_length=20)),
                ("quantity", models.PositiveIntegerField()),
                ("reference", models.CharField(blank=True, max_length=180)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="inventory.batch")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="branches.branch")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="inventory.item")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inventory_movements", to=settings.AUTH_USER_MODEL)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="DispenseItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.batch")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="branches.branch")),
                ("dispense", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="inventory.dispense")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.item")),
            ],
            options={"abstract": False},
        ),
        migrations.AddIndex(model_name="brand", index=models.Index(fields=["branch", "name"], name="inventory_b_branch__d4ac5f_idx")),
        migrations.AddConstraint(model_name="brand", constraint=models.UniqueConstraint(fields=("branch", "name"), name="inventory_unique_brand_per_branch")),
        migrations.AddIndex(model_name="category", index=models.Index(fields=["branch", "name"], name="inventory_c_branch__c1ad4c_idx")),
        migrations.AddConstraint(model_name="category", constraint=models.UniqueConstraint(fields=("branch", "name"), name="inventory_unique_category_per_branch")),
        migrations.AddIndex(model_name="supplier", index=models.Index(fields=["branch", "name"], name="inventory_s_branch__7454a5_idx")),
        migrations.AddConstraint(model_name="supplier", constraint=models.UniqueConstraint(fields=("branch", "name"), name="inventory_unique_supplier_per_branch")),
        migrations.AddIndex(model_name="item", index=models.Index(fields=["branch", "item_name"], name="inventory_i_branch__f24aab_idx")),
        migrations.AddIndex(model_name="item", index=models.Index(fields=["branch", "generic_name"], name="inventory_i_branch__f0b4cd_idx")),
        migrations.AddIndex(model_name="item", index=models.Index(fields=["branch", "barcode"], name="inventory_i_branch__b8f8c9_idx")),
        migrations.AddIndex(model_name="item", index=models.Index(fields=["branch", "is_active"], name="inventory_i_branch__f8607e_idx")),
        migrations.AddIndex(model_name="batch", index=models.Index(fields=["branch", "item", "exp_date"], name="inventory_b_branch__03615e_idx")),
        migrations.AddIndex(model_name="batch", index=models.Index(fields=["branch", "exp_date"], name="inventory_b_branch__4ec1df_idx")),
        migrations.AddIndex(model_name="batch", index=models.Index(fields=["branch", "quantity_remaining"], name="inventory_b_branch__4a3512_idx")),
        migrations.AddIndex(model_name="batch", index=models.Index(fields=["branch", "batch_number"], name="inventory_b_branch__f81a6b_idx")),
        migrations.AddConstraint(model_name="batch", constraint=models.UniqueConstraint(fields=("branch", "item", "batch_number"), name="inventory_unique_batch_per_item_per_branch")),
        migrations.AddIndex(model_name="stockmovement", index=models.Index(fields=["branch", "movement_type", "date"], name="inventory_s_branch__618639_idx")),
        migrations.AddIndex(model_name="stockmovement", index=models.Index(fields=["branch", "item", "date"], name="inventory_s_branch__ca2bee_idx")),
        migrations.AddIndex(model_name="dispense", index=models.Index(fields=["branch", "date"], name="inventory_d_branch__9bc643_idx")),
        migrations.AddIndex(model_name="dispenseitem", index=models.Index(fields=["branch", "item"], name="inventory_d_branch__47f66c_idx")),
        migrations.AddIndex(model_name="dispenseitem", index=models.Index(fields=["branch", "batch"], name="inventory_d_branch__2a41fa_idx")),
    ]
