# Generated by Django 4.2.29 on 2026-03-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_medical_stores_framework'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batch',
            new_name='inventory_b_branch__0f095e_idx',
            old_name='inventory_b_branch__03615e_idx',
        ),
        migrations.RenameIndex(
            model_name='batch',
            new_name='inventory_b_branch__758888_idx',
            old_name='inventory_b_branch__4ec1df_idx',
        ),
        migrations.RenameIndex(
            model_name='batch',
            new_name='inventory_b_branch__f6b065_idx',
            old_name='inventory_b_branch__4a3512_idx',
        ),
        migrations.RenameIndex(
            model_name='batch',
            new_name='inventory_b_branch__7e6a43_idx',
            old_name='inventory_b_branch__f81a6b_idx',
        ),
        migrations.RenameIndex(
            model_name='brand',
            new_name='inventory_b_branch__669dc4_idx',
            old_name='inventory_b_branch__d4ac5f_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='inventory_c_branch__6261c3_idx',
            old_name='inventory_c_branch__c1ad4c_idx',
        ),
        migrations.RenameIndex(
            model_name='dispense',
            new_name='inventory_d_branch__5af727_idx',
            old_name='inventory_d_branch__9bc643_idx',
        ),
        migrations.RenameIndex(
            model_name='dispenseitem',
            new_name='inventory_d_branch__af050e_idx',
            old_name='inventory_d_branch__47f66c_idx',
        ),
        migrations.RenameIndex(
            model_name='dispenseitem',
            new_name='inventory_d_branch__954e4e_idx',
            old_name='inventory_d_branch__2a41fa_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='inventory_i_branch__6a3199_idx',
            old_name='inventory_i_branch__f24aab_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='inventory_i_branch__e7ecc2_idx',
            old_name='inventory_i_branch__f0b4cd_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='inventory_i_branch__c50db1_idx',
            old_name='inventory_i_branch__b8f8c9_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='inventory_i_branch__74208f_idx',
            old_name='inventory_i_branch__f8607e_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_branch__a0dd80_idx',
            old_name='inventory_s_branch__618639_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_branch__541adf_idx',
            old_name='inventory_s_branch__ca2bee_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='inventory_s_branch__d88e7f_idx',
            old_name='inventory_s_branch__7454a5_idx',
        ),
    ]
