# Generated by Django 4.2.29 on 2026-03-22 16:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_inventory_b_branch__03615e_idx_inventory_b_branch__0f095e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='pack_size_units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='batch',
            name='packs_received',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='batch',
            name='purchase_price_per_pack',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='batch',
            name='wholesale_price_per_pack',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='item',
            name='default_pack_size_units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
