# Generated by Django 4.2.29 on 2026-03-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('clinic_address', models.TextField()),
                ('clinic_phone', models.CharField(max_length=30)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('color_scheme', models.CharField(default='#0d6efd', max_length=32)),
                ('is_initialized', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
