# Generated by Django 4.2.29 on 2026-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0004_systemsettings_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sidebar_color',
            field=models.CharField(default='#1e293b', max_length=32),
        ),
    ]
