# Generated by Django 4.2.29 on 2026-03-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0005_systemsettings_sidebar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sidebar_text_color',
            field=models.CharField(default='#94a3b8', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sidebar_text_size',
            field=models.DecimalField(decimal_places=2, default=0.81, max_digits=3),
        ),
    ]
