# Generated by Django 4.2.29 on 2026-03-15 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


BODY_REGION_BY_EXAMINATION = {
    "chest_xray": "Chest",
    "skull_xray": "Skull",
    "spine_xray": "Spine",
    "pelvic_xray": "Pelvis",
    "hand_xray": "Hand",
    "leg_xray": "Leg",
    "knee_xray": "Knee",
    "foot_xray": "Foot",
    "abdominal_xray": "Abdomen",
    "abdominal_ultrasound": "Abdomen",
    "pelvic_ultrasound": "Pelvis",
    "obstetric_ultrasound": "Obstetric",
    "kidney_ultrasound": "Kidneys",
    "prostate_ultrasound": "Prostate",
    "breast_ultrasound": "Breast",
    "thyroid_ultrasound": "Thyroid",
    "doppler_ultrasound": "Vascular",
}


def populate_imaging_request_metadata(apps, schema_editor):
    ImagingRequest = apps.get_model("radiology", "ImagingRequest")
    status_map = {
        "in_progress": "scanning",
        "performed": "reporting",
        "reported": "completed",
    }
    priority_map = {
        "routine": "normal",
        "stat": "urgent",
    }

    for imaging_request in ImagingRequest.objects.all().order_by("pk"):
        update_fields = []

        if not imaging_request.request_identifier:
            imaging_request.request_identifier = (
                f"BR{imaging_request.branch_id or 0}-RAD-{imaging_request.pk:06d}"
            )
            update_fields.append("request_identifier")

        normalized_status = status_map.get(imaging_request.status)
        if normalized_status and normalized_status != imaging_request.status:
            imaging_request.status = normalized_status
            update_fields.append("status")

        normalized_priority = priority_map.get(imaging_request.priority)
        if normalized_priority and normalized_priority != imaging_request.priority:
            imaging_request.priority = normalized_priority
            update_fields.append("priority")

        if imaging_request.specific_examination and not imaging_request.body_region:
            body_region = BODY_REGION_BY_EXAMINATION.get(
                imaging_request.specific_examination
            )
            if body_region:
                imaging_request.body_region = body_region
                update_fields.append("body_region")

        if update_fields:
            imaging_request.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("branches", "0002_remove_branch_date_created"),
        ("radiology", "0002_imagingrequest_visit"),
    ]

    operations = [
        migrations.CreateModel(
            name="RadiologyComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "radiology_comparisons",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RadiologyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_file",
                    models.FileField(
                        blank=True, null=True, upload_to="radiology/attachments/"
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="radiology/reports/"
                    ),
                ),
                (
                    "file_kind",
                    models.CharField(
                        choices=[
                            ("dicom", "DICOM"),
                            ("image", "Image"),
                            ("pdf", "PDF Report"),
                            ("clip", "Ultrasound Clip"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("machine_used", models.CharField(blank=True, max_length=120)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "radiology_images",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RadiologyNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("scan_completed", "Scan Completed"),
                            ("report_uploaded", "Report Uploaded"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RadiologyQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("scheduled", "Scheduled"),
                            ("patient_arrived", "Patient Arrived"),
                            ("scanning", "Scanning"),
                            ("reporting", "Reporting"),
                            ("completed", "Completed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("patient_arrived_at", models.DateTimeField(blank=True, null=True)),
                ("scan_started_at", models.DateTimeField(blank=True, null=True)),
                ("reporting_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "radiology_queue",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RadiologyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imaging_type",
                    models.CharField(
                        choices=[("xray", "X-Ray"), ("ultrasound", "Ultrasound")],
                        max_length=20,
                    ),
                ),
                ("examination_code", models.CharField(max_length=60)),
                ("examination_name", models.CharField(max_length=120)),
                ("body_region", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "radiology_types",
                "abstract": False,
            },
        ),
        migrations.RenameIndex(
            model_name="imagingrequest",
            new_name="radiology_r_branch__661560_idx",
            old_name="radiology_i_branch__5f2c7f_idx",
        ),
        migrations.RenameIndex(
            model_name="imagingresult",
            new_name="radiology_r_branch__33fff5_idx",
            old_name="radiology_i_branch__d66bb6_idx",
        ),
        migrations.AddField(
            model_name="imagingrequest",
            name="additional_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="imagingrequest",
            name="body_region",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="imagingrequest",
            name="last_menstrual_period",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagingrequest",
            name="pregnancy_weeks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagingrequest",
            name="request_identifier",
            field=models.CharField(blank=True, default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagingrequest",
            name="requested_department",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="imagingrequest",
            name="specific_examination",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="imagingrequest",
            name="suspected_condition",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="imagingrequest",
            name="symptoms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="imagingresult",
            name="clinical_information",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="imagingresult",
            name="examination",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="imagingresult",
            name="impression",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="imagingresult",
            name="machine_used",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="imagingresult",
            name="notified_requesting_doctor_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagingresult",
            name="report_file",
            field=models.FileField(
                blank=True, null=True, upload_to="radiology/reports/"
            ),
        ),
        migrations.AlterField(
            model_name="imagingrequest",
            name="imaging_type",
            field=models.CharField(
                choices=[("xray", "X-Ray"), ("ultrasound", "Ultrasound")], max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="imagingrequest",
            name="priority",
            field=models.CharField(
                choices=[("normal", "Normal"), ("urgent", "Urgent")],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="imagingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("scheduled", "Scheduled"),
                    ("patient_arrived", "Patient Arrived"),
                    ("scanning", "Scanning"),
                    ("reporting", "Reporting"),
                    ("completed", "Completed"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="imagingresult",
            name="image_file",
            field=models.FileField(blank=True, null=True, upload_to="radiology/scans/"),
        ),
        migrations.RunPython(
            populate_imaging_request_metadata, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="imagingrequest",
            name="request_identifier",
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddIndex(
            model_name="imagingrequest",
            index=models.Index(
                fields=["branch", "request_identifier"],
                name="radiology_r_branch__5c60ff_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="imagingrequest",
            table="radiology_requests",
        ),
        migrations.AlterModelTable(
            name="imagingresult",
            table="radiology_reports",
        ),
        migrations.AddField(
            model_name="radiologytype",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="branches.branch"
            ),
        ),
        migrations.AddField(
            model_name="radiologyqueue",
            name="assigned_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_radiology_queue_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="radiologyqueue",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="branches.branch"
            ),
        ),
        migrations.AddField(
            model_name="radiologyqueue",
            name="imaging_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_entry",
                to="radiology.imagingrequest",
            ),
        ),
        migrations.AddField(
            model_name="radiologynotification",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="branches.branch"
            ),
        ),
        migrations.AddField(
            model_name="radiologynotification",
            name="imaging_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="radiology.imagingrequest",
            ),
        ),
        migrations.AddField(
            model_name="radiologynotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="radiology_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="radiologyimage",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="branches.branch"
            ),
        ),
        migrations.AddField(
            model_name="radiologyimage",
            name="imaging_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="radiology.imagingrequest",
            ),
        ),
        migrations.AddField(
            model_name="radiologyimage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_radiology_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="radiologycomparison",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="branches.branch"
            ),
        ),
        migrations.AddField(
            model_name="radiologycomparison",
            name="compared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="radiology_comparisons_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="radiologycomparison",
            name="current_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparison_current_request_set",
                to="radiology.imagingrequest",
            ),
        ),
        migrations.AddField(
            model_name="radiologycomparison",
            name="previous_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparison_previous_request_set",
                to="radiology.imagingrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="radiologytype",
            index=models.Index(
                fields=["branch", "imaging_type", "is_active"],
                name="radiology_t_branch__28d366_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="radiologytype",
            index=models.Index(
                fields=["branch", "body_region"], name="radiology_t_branch__a6093a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="radiologytype",
            constraint=models.UniqueConstraint(
                fields=("branch", "examination_code"),
                name="radiology_unique_exam_code_per_branch",
            ),
        ),
        migrations.AddIndex(
            model_name="radiologyqueue",
            index=models.Index(
                fields=["branch", "status", "scheduled_for"],
                name="radiology_q_branch__abf771_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="radiologyqueue",
            index=models.Index(
                fields=["branch", "completed_at"], name="radiology_q_branch__72e895_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="radiologynotification",
            index=models.Index(
                fields=["branch", "recipient", "is_read", "created_at"],
                name="radiology_r_branch__f46f80_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="radiologynotification",
            index=models.Index(
                fields=["branch", "event_type", "created_at"],
                name="radiology_r_branch__208f46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="radiologyimage",
            index=models.Index(
                fields=["branch", "file_kind", "upload_date"],
                name="radiology_i_branch__f9ab54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="radiologyimage",
            index=models.Index(
                fields=["imaging_request", "upload_date"],
                name="radiology_i_imaging_62ef34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="radiologycomparison",
            index=models.Index(
                fields=["branch", "created_at"], name="radiology_c_branch__d6b2da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="radiologycomparison",
            index=models.Index(
                fields=["current_request", "previous_request"],
                name="radiology_c_current_3ac52d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="radiologycomparison",
            constraint=models.UniqueConstraint(
                fields=("current_request", "previous_request"),
                name="radiology_unique_request_comparison",
            ),
        ),
    ]
