# Generated by Django 4.2.29 on 2026-04-03 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0003_branch_shift_variance_threshold'),
        ('admission', '0004_nursingnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='bed',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('ward_type', models.CharField(choices=[('general', 'General'), ('maternity', 'Maternity'), ('paediatric', 'Paediatric'), ('icu', 'ICU'), ('surgical', 'Surgical'), ('emergency', 'Emergency'), ('private', 'Private')], default='general', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
            ],
            options={
                'abstract': False,
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='admission.ward')),
            ],
            options={
                'ordering': ['ward', 'bed_number'],
                'abstract': False,
                'unique_together': {('ward', 'bed_number')},
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='bed_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='admission.bed'),
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °C', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pulse_rate', models.PositiveSmallIntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, help_text='SpO2 %', null=True)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='admission.admission')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vital_sign_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['admission', '-created_at'], name='admission_v_admissi_db1deb_idx')],
            },
        ),
    ]
