# Generated by Django 4.2.8 on 2026-04-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_shift_variance_threshold'),
        ('billing', '0020_alter_cashdrawer_service_type_and_more'),
        ('admission', '0005_alter_admission_bed_alter_admission_ward_ward_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='last_billed_date',
            field=models.DateField(blank=True, help_text='The last date a daily ward charge was billed for.', null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='ward_obj',
            field=models.ForeignKey(blank=True, help_text='Links to the Ward for billing rate lookup.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='admission.ward'),
        ),
        migrations.AddField(
            model_name='ward',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Planned bed capacity'),
        ),
        migrations.AddField(
            model_name='ward',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily bed charge for this ward (set from Settings).', max_digits=12),
        ),
        migrations.AddField(
            model_name='ward',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='ward_category',
            field=models.CharField(choices=[('ordinary', 'Ordinary'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='ordinary', max_length=10),
        ),
        migrations.CreateModel(
            name='AdmissionDailyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ward_category', models.CharField(choices=[('ordinary', 'Ordinary'), ('vip', 'VIP'), ('vvip', 'VVIP')], max_length=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_charges', to='admission.admission')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_charges', to='billing.invoicelineitem')),
            ],
            options={
                'ordering': ['-charge_date'],
                'abstract': False,
                'unique_together': {('admission', 'charge_date')},
            },
        ),
    ]
