# Generated by Django 4.2.29 on 2026-04-05 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0003_branch_shift_variance_threshold'),
        ('admission', '0006_admission_last_billed_date_admission_ward_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('intake_oral', 'Oral Intake'), ('intake_iv', 'IV Fluids'), ('output_urine', 'Urine Output'), ('output_drain', 'Drain Output'), ('output_vomit', 'Vomiting'), ('output_other', 'Other Output')], max_length=20)),
                ('amount_ml', models.PositiveIntegerField(help_text='Amount in millilitres')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_outputs', to='admission.admission')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='io_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WardRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('findings', models.TextField(help_text='Clinical findings during the round')),
                ('plan', models.TextField(blank=True, help_text='Management plan going forward')),
                ('round_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_rounds', to='admission.admission')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ward_rounds_conducted', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_rounds_assisted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-round_time'],
                'abstract': False,
                'indexes': [models.Index(fields=['admission', '-round_time'], name='admission_w_admissi_366da7_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg, 10ml', max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous (IV)'), ('im', 'Intramuscular (IM)'), ('sc', 'Subcutaneous (SC)'), ('topical', 'Topical'), ('inhaled', 'Inhaled'), ('rectal', 'Rectal'), ('sublingual', 'Sublingual'), ('other', 'Other')], default='oral', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('given', 'Given'), ('refused', 'Patient Refused'), ('held', 'Held'), ('not_available', 'Not Available')], default='given', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_administrations', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='admission.admission')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
            ],
            options={
                'ordering': ['-scheduled_time'],
                'abstract': False,
                'indexes': [models.Index(fields=['admission', '-scheduled_time'], name='admission_m_admissi_aa7b40_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('medication', 'Medication'), ('investigation', 'Investigation'), ('nursing', 'Nursing Care'), ('diet', 'Diet'), ('activity', 'Activity / Mobility'), ('monitoring', 'Monitoring'), ('other', 'Other')], default='nursing', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=10)),
                ('instruction', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('carried_out', 'Carried Out'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('carried_out_at', models.DateTimeField(blank=True, null=True)),
                ('carried_out_notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_orders', to='admission.admission')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('carried_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_orders_executed', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_orders_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['admission', 'status'], name='admission_d_admissi_f73320_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('shift', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('evening', 'Evening Shift')], default='day', max_length=10)),
                ('general_condition', models.TextField(help_text="Patient's overall condition during this shift")),
                ('diet_intake', models.CharField(blank=True, help_text='e.g. Good, Poor, NPO', max_length=200)),
                ('fluid_intake', models.CharField(blank=True, help_text='IV / oral fluids given', max_length=200)),
                ('fluid_output', models.CharField(blank=True, help_text='Urine, drain output, etc.', max_length=200)),
                ('mobility', models.CharField(blank=True, help_text='e.g. Ambulatory, Bed rest', max_length=200)),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, help_text='Scale 0–10', null=True)),
                ('wound_status', models.TextField(blank=True, help_text='Wound/surgical site status if applicable')),
                ('concerns', models.TextField(blank=True, help_text='Any concerns or escalation needs')),
                ('handover_notes', models.TextField(blank=True, help_text='Notes for the incoming nurse')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='admission.admission')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
                'abstract': False,
                'unique_together': {('admission', 'report_date', 'shift')},
            },
        ),
    ]
