# Generated by Django 4.2.29 on 2026-03-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visit',
            new_name='visits_visi_branch__6ac241_idx',
            old_name='visits_visi_branch__eb95ff_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visits_visi_patient_93b6f4_idx',
            old_name='visits_visi_patient_1a0a54_idx',
        ),
        migrations.RenameIndex(
            model_name='visitqueueevent',
            new_name='visits_visi_branch__e7dbef_idx',
            old_name='visits_visi_branch__aa5238_idx',
        ),
        migrations.RenameIndex(
            model_name='visitqueueevent',
            new_name='visits_visi_visit_i_fcdb2e_idx',
            old_name='visits_visi_visit_id_11f940_idx',
        ),
    ]
