# Generated by Django 4.2.8 on 2026-03-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0002_remove_branch_date_created"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visit_number", models.CharField(max_length=32, unique=True)),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("outpatient", "Outpatient"),
                            ("emergency", "Emergency"),
                            ("admission", "Admission"),
                        ],
                        default="outpatient",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting_triage", "Waiting Triage"),
                            ("in_triage", "In Triage"),
                            ("waiting_doctor", "Waiting Doctor"),
                            ("lab_requested", "Lab Requested"),
                            ("radiology_requested", "Radiology Requested"),
                            ("waiting_pharmacy", "Waiting Pharmacy"),
                            ("billing_queue", "Billing Queue"),
                            ("admission_queue", "Admission Queue"),
                            ("admitted", "Admitted"),
                            ("completed", "Completed"),
                        ],
                        default="waiting_triage",
                        max_length=30,
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["branch", "status", "check_in_time"],
                        name="visits_visi_branch__eb95ff_idx",
                    ),
                    models.Index(
                        fields=["patient", "check_in_time"],
                        name="visits_visi_patient_1a0a54_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitQueueEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(max_length=30)),
                ("moved_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="branches.branch",
                    ),
                ),
                (
                    "moved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["branch", "to_status", "moved_at"],
                        name="visits_visi_branch__aa5238_idx",
                    ),
                    models.Index(
                        fields=["visit", "moved_at"],
                        name="visits_visi_visit_id_11f940_idx",
                    ),
                ],
            },
        ),
    ]
